- src/components/Navbar/Navbar.css
issue #196 
before:
after:
display: flex was being overwritten. fixed it with an important tag.
> fixed navbar display flex that was overwritten by some other style

- src/runtime.js
In this commit, I have addressed the module import error that occurs in Mac and Linux systems by creating a runtime.js file. This file is placed in the project repository's src directory. By doing so, we ensure that the relative imports remain within the src directory, as required by the project structure.
This contribution aims to resolve the issue that arises when attempting to import the react-refresh module from outside the src directory. The runtime.js file serves as a symlink or reference to the actual react-refresh module located in the node_modules directory.
By adding the runtime.js file in the project repository, we provide a convenient and consistent solution for developers working on Mac and Linux systems. This improvement ensures that the project can be successfully executed …
> #285 Add runtime.js file to resolve module import error in Mac and Linux Systems

- src/components/Home/BkCards/CardContent/CardContent.js
Previously the images in the cards were not of equal sizes 
Have Fixed the issue by giving them a height equal to 40% of the container
Before
After
Issue Reference #356
> Cards Size Enhanced

- src/components/Navbar/Navbar.css
Closes #418 
This fixes the search bar on phones and also the menu looks more aesthetic.
Before:
After:
> Closes #418

- src/components/About/Download.css
Closes #426 
The hover effect on download app buttons blends the play-store and app-store icons,It has been fixed with CSS.
before:
after:
> Fixed #426 Hover effect on download app buttons blends play-store and app-store icon

- src/components/BookList/BookList.js
- src/components/Navbar/Navbar.css
Closes #430 
#430
BookList.js
This fixes the problem of alignment of search on mobile devices.
Navbar.css
Also, I again checked and found that the height should not be in term of vh as it is breaking in different vh 
So, I again updated the height in terms of pixels. 
Before:
After:
> Closes #430 and fixes the navbar.css & BookList.js

- src/components/About/Testimonial.css
Closes #510 
The testimonials section when not being hovered showed an unpleasant shadow making it appear split into sections. The shadow had been removed in this commit.
| Before | After |
| -- | -- |
| ![image](https://github.com/rohansx/informatician/assets/57594891/fde4d5e0-bf84-422a-8744-91cb7caf6401) | ![image](https://github.com/rohansx/informatician/assets/57594891/3ceeab31-1eaf-43e0-b39c-df16760ea59e) |
> Fixed issue #510

- src/components/BookList/BookList.css
Closes #553 
While hovering over the search icon on the books page, the search bar was supposed to expand according to the animation set on the icon but it was behaving weirdly. I fixed it by making some changes in the styling of the search icon while hovering over it.
screenshot
video
https://github.com/rohansx/informatician/assets/77545230/a8eeb153-e3ec-4699-8a93-233205bee9cc
> fixed bug in books page search bar

- src/components/Body.js
- src/components/Cookie.css
- src/components/Terms&Service.js
- src/components/TermsAndService.css
* Closes #575 
The dark mode is now added to Terms and Cookies pages. Also there were alignment issues and typo in the "Cookies" page which is resolved now.
Screenshots added for reference:
1. Terms and Service Page updated:
2. Alignment issue on Cookies page and dark mode updated:
Before:
After:
3. Typo 
Before:
(no space before email):
After:
> Dark mode added to Terms and Cookies pages with minor issues resolved

- src/components/Body.js
- src/components/Home/SingleBk/SingleBk.js
- src/components/Home/SingleBk/SingleBk1.js
- src/components/Home/SingleBk/SingleBk2.js
- src/components/Home/SingleBk/SingleBk3.js
- src/components/Home/SingleBk/SingleBk4.js
- src/components/Home/SingleBk/SingleBk5.js
- src/components/Home/SingleBk/SingleBk6.js
- src/components/Home/SingleBk/SingleBk7.js
- src/components/Home/SingleBk/SingleBk8.js
- src/components/Home/SingleBk/SingleBk9.js
- src/components/Team/ContCard.js
- src/components/Team/Contributor.css
- src/components/Team/Contributor.js
- src/components/Team/Team.js
* Closes #577 
Added the dark mode implementation to the pages - Our team, privacy policy and individual book pages.
The details page of all the 10 books were changed as there were many bugs in the dark mode implementation and styling.
Adding the screenshots for reference:
1. Our Team:
Before:
After: 
2. Privacy Page:
Before:
After:
3. Book Details: (All the 10 books - 10 files)
Before:
After:
> Solved all the dark mode issues - Our Team | Privacy Policy | Books

- src/components/Body.js
- src/components/faq.js
* Closes #587 
The dark mode feature was not applied to the FAQs. Resolved this styling mismatch.
> Added dark mode to FAQs

- src/components/Home/BkCards/BkCards.css
Closes #649 
Fixed the unnecessary height increment of entire element on hovering the child card element. 
Before:
https://github.com/rohansx/informatician/assets/77684943/be1b50d3-0d09-4220-9faa-76746bc0b6c7
After:
https://github.com/rohansx/informatician/assets/77684943/87b75e28-4fbf-44fb-9a7f-98a2fd14213a
> Fixed Card UI in Slider

- src/components/Contactus.css
* Closes #656 
The dark mode was not applicable to the contact page. Resolved the same by updating CSS styles.
> Resolved dark mode issue on contact page

- src/components/BookList/BookList.css
- src/components/BookList/BookList.js
Closes #751 
I have added a infinite loop slider to the quote section and fixed the last quote card's visibility which was not fully visible.
- `src/components/BookList/BookList.css`
- `src/components/BookList/BookList.js`
[Informatician.webm](https://github.com/rohansx/informatician/assets/130365071/ffc4f781-7ef4-4c8d-a566-b8a7a4d37b74)
Please review this PR 
Thanks
> feat: add slider to quote section

- src/components/Footer.js
Closes #800 
- Added `aria-label` attribute for social anchors like github & twitter
- The `aria-label` attribute is important for screen readers because it provides a text label for an object, such as `a` with social icons. When a screen reader encounters the object, the `aria-label` text is read so that the user will know what it is. 
- This is important for people who are blind or have low vision, as they rely on screen readers to access the web.
- Improved `title` attribute's data, because the title attribute is intended to provide additional information to screen reader users.
- And along with that i added `rel` for the anchors which are lacking them to ensure best practices for crawlers
- Because adding the `rel="noopener noreferrer"` attribute can help to protect this website from …
> [FEAT]: MAKE SOCIAL ANCHORS ACCESSIBLE ON FOOTER ✨

- src/components/FAQ/faq.css
Closes #843 
Added the color to text which was not visible in light mode.
before:
after:
- [x ] I have conducted a self-review of my code.
> Added text color to the FAQ section in light mode  issue-843

- src/components/Footer/NewsLetter/NewsLetter.css
- src/components/Newsletter.js
css issue fix for subscribe button and email id bug no:- #895
and added on hover subscribe button become red in background 
on hover
> css issue fix for subscribe button and email id bug no:- #895

- src/components/BookList/BookList.css
- src/components/BookList/BookList.js
#887 
I have improved the Ui of the quotes cards on the books page especially in the dark mode, and made it visible properly.
> Quotes cards in Dark mode

- src/pages/Contact/Contactus.js
Close #1040 
- Added `aria-label` attribute for social anchors like github & twitter
- The `aria-label` attribute is important for screen readers because it provides a text label for an object, such as `a` with social icons. When a screen reader encounters the object, the `aria-label` text is read so that the user will know what it is. 
- This is important for people who are blind or have low vision, as they rely on screen readers to access the web.
- Improved `title` attribute's data, because the title attribute is intended to provide additional information to screen reader users.
- And along with that i added `rel` for the anchors which are lacking them to ensure best practices for crawlers
- Because adding the `rel="noopener noreferrer"` attribute can help to protect this website from …
> feat: made social anchors accessible on contact us page ✨

- src/pages/Login/Login.jsx
- Fixed the margin bug applied for `Login with Google` button on Login Page.
<table role="table">
<thead>
<tr>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr>
<td align="center"><strong>BEFORE</strong></td>
<td align="center"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/92252895/256084635-827d1d5d-d4ad-406e-8086-7f5af3ed91bd.png"><img src="https://user-images.githubusercontent.com/92252895/256084635-827d1d5d-d4ad-406e-8086-7f5af3ed91bd.png" alt="BEFORE" style="max-width: 100%;"></a></td>
</tr>
<tr>
<td align="center"><strong>AFTER</strong></td>
<td align="center"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/92252895/256084617-ab12e29c-ce1e-493a-a590-e18ccf7ee7d9.png …
> fix: incorrect margin for login with google button on login page 🛠️

- components/Upload/Upload.js
Closes #1082 
Users can see the upload book option, after filling the entire form while submitting it shows error, authorization failed.
Instead of this, we can show a warning beforehand that you haven't logged in and first you need to login to proceed with adding book.
This pr fixes the issue
> added login alert fixes issue #1082

- app/addBooks/page.jsx
Closes #1125
- Made input elements of Add Books form accessible by adding appropriate `label` elements.
- `label` elements are attached with their necessary input fields by using attributes like `for`, `id` & `name`.
- Overall, this PR is intended to make the entire add books form accessible for screen readers.
- We can't capture accessibility changes through screenshots as opposed to code changes since accessibility modifications are often imperceptible to the user, as their purpose is to assist disabled individuals.
> feat: made add books form accessible ✨ 

- components/Navbar/Navbar.js
Closes #1086
This PR effectively addresses the issue where the suggestion drop-down fails to close automatically after user selection, causing frustration and obstructing the view of underlying content. To enhance usability and user satisfaction, I have implemented a solution to automatically close the drop-down upon selection. With this fix, users will no longer need to manually close the drop-down, resulting in a smoother and more seamless interaction with the application. 🌟🙌
1. Fixed not automatically Closing Issue
2. Additionally, I have added functionality to remove text when the user clicks on one of the result options, 
3. Furthermore, I have refactored the drop-down/results to improve overall performance and code organization.
Your feedback and review on this PR are highly …
> [FIX] : 🚀 Automatic Suggestion Dropdown Closure - Improved User Experience 🔧📝

- .github/ISSUE_TEMPLATE/bug.yml
Closes #1177 
- Fixed the wrong Contributing Guidelines documentation read link which navigates to `LinksHub` is now solved and navigates to `Informatician`
> fix: wrong contributing guidelines documentation link on bug issue template ⚒️ 

- components/Footer/Footer.css
Closes #1170
- Fixed the bad contrast color applied for headings on FAQ Page.
|BEFORE|AFTER|
|:---:|:---:|
| ![](https://user-images.githubusercontent.com/92252895/257397198-3866cbed-92ac-4e66-a96f-d36aa18356be.png) | ![image](https://github.com/rohansx/informatician/assets/92252895/dc69ec70-f4fe-498f-8fee-567e421ceed0) |
> fix: bad contrast color applied for headings on faq page ⚒️

- components/Footer/Footer.js
Closes #1210 
- Fixed the misaligned copyright container and it's elements properly for mobile devices.
- Used Tailwind's Responsive utility classes like `sm` for mobile devices and `lg` to target tablets and desktops.
|||
|:---:|:---:|
|![](https://user-images.githubusercontent.com/92252895/257816849-3f9a0beb-2519-4cf5-a483-db3dbe1872c0.png)|![](https://user-images.githubusercontent.com/92252895/257817016-eb12b3f5-d0aa-42e1-ab78-d8ee73c37927.png)|
> fix: missaligned copyright and it's elements on footer ⚒️✨ 

- app/team/Contributors.js
Closes #1198
- Fixed the bad contrast color applied for Contributors details on team page
|BEFORE|AFTER|
|:---:|:---:|
|![Screen Shot 2023-08-02 at 18 02 16](https://github.com/rohansx/informatician/assets/92252895/32db83aa-96d4-48ef-a100-d8c8d6719fc6)|![Screen Shot 2023-08-02 at 18 01 23](https://github.com/rohansx/informatician/assets/92252895/92709732-563b-4e17-b3a4-eb262a199eff)|
> fix: bad contrast color for contributors details on team page ⚒️✨ 

- components/theme/theme-toggle.jsx
Closes #1209 
- Fixed the incorrect placement of theme toggle button for Mobile devices.
|BEFORE|AFTER|
|:---:|:---:|
| ![image](https://github.com/rohansx/informatician/assets/92252895/a2208775-c9f1-4c9e-98de-2a5bef937bcf) | ![image](https://github.com/rohansx/informatician/assets/92252895/8d5aa7b4-3f2a-451a-b2e6-ee10d0de1ddf) |
> fix: incorrect placement of theme toggle button on mobile ⚒️ ✨ 

- app/about/page.jsx
- components/About/Feature.css
- components/About/Testimonial.js
Closes #1164 **Features Slider not responsive**
Hey @SiddhantPawar03 , I want to create this PR for issue #1164  but when I pull the latest changes it seems that the feature slider has been made responsive so I could not contribute to that specifically.
Instead what I did is I took a good scan of the entire about page and find some typos and minor style bugs that I fix in this PR on behalf of that issue.
**The changes I made are:** 
**Some little changes in the spelling of content that sound typos while reading
And
I fixed the uneven size of the feature slider as shown below screenshot.**
**Before:**
**After:**
**I am contributing as a gssoc23 contributor, So if you think it is a valid PR and can be merged with gssoc points then it will be great. But if you think gssoc23 labels cannot be …
> Changes in Features
