rohansx/informatician

CONTRIBUTION.md
README.md
STYLE_GUIDE.md

Hello,
I have created CONTRIBUTION.md, STYLE_GUIDE.md and updated README.md files in the contribution-style-furqanhun branch.  This was done in response to issue #1 where the owner asked for help with "create contributing.md file for this repository" Here is a brief summary of what I did:
- In [CONTRIBUTION.md](https://github.com/FurqanHun/informatician/blob/contribution-style-furqanhun/CONTRIBUTION.md), I added some guidelines for contributing to the informatician project. I explained how to report bugs, suggest enhancements, make code contributions, improve documents and how to get help. Also I added a thank you note appreciating the contributors and encouraging others to contribute.
- In [STYLE_GUIDE.md](https://github.com/FurqanHun/informatician/blob/contribution-style-furqanhun/STYLE_ …

added CONTRIBUTION.md, STYLE_GUIDE.md & updated REAMDE.md - Furqanhun

---

public/index.html
src/components/Footer.css

Improved Footer's UI, Placed social icons on right place added some margin to other components.

Footer styling

---

public/index.html

Changed the title of the project. Directly from index.html

Changed the title of the Project

---

src/components/Footer.js
src/components/Navbar.js

Naming issue of the website (Issue #66) solved

#66 solved

---

src/components/Footer.js

fixes: #73 
Made the footer link active, now it redirects to the about us page.

made footer link active

---

src/components/Footer.js

fixes: #74 
Added the link to file an issue to GitHub directly from the website.

Added link to file an issue to the github

---

package-lock.json
package.json
src/App.js
src/components/About.js
src/components/BookList.js
src/components/ScrollButton.css
src/components/ScrollButton.js

* Resolves the issue #75 
I've added the scroll to top button on the bottom-right corner of each of the pages.
Image for reference:

Added the Scroll to top button

---

src/components/Footer.js

This pr solves issue #142 . I have made footer responsive till minimum width 320px. Also added links. Please review and merge this request.

Footer made responsive Solves #142

---

src/components/Footer.js
src/components/Navbar.js

solved navbar redirecting issue, replaced repeating support in footer

---

.github/dependabot.yml

Fixes #191 
@rohansx pls review

Depandabot added

---

package-lock.json
src/components/Contactus.css
src/components/Contactus.js

issue solved #174 
You can see this here
On Mobile Screen

Contact us page improvement

---

.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/close_old_issues.yaml

Fixes #190 
@rohansx kindly review

Feature request template added

---

.github/ISSUE_TEMPLATE/bug.yml

fixes #211 
@rohansx kindly review

Issue template for bug request added

---

src/components/Navbar/Navbar.js

#214 fixed

---

.github/workflows/greetings.yml

workflow for greeting added

---

src/components/Navbar/Navbar.js

@rohansx navbar highlighting is fixed

#216 fixed

---

README.md

- Fixes #244 
- Added table of contents and back-to-top links in Readme.md

Table of contents and back-to-top links in ReadMe.md

---

src/components/Footer/Footer.js
src/components/develop.js

this will be displayed on all social media platforms icons if clicked and other playstore one too
till they are made.

#249 custom page designed and linked

---

package-lock.json
src/components/Footer/Footer.js

Fix of footer buttons not scrolling to top

---

src/index.css

Done with the scrollbar, hope it looks better now :)

Enhanced the scrollbar

---

src/components/Home/BkCards/BkCards.js

@rohansx pls review the code changes
I also have an idea to use an array and a single component to render the books instead of rewriting
we can have an array of objects with properties

pause autoplay when mouse over the book cards

---

src/components/Footer/Footer.js

* Resolves the issue - #238 
Added a function to automatically fetch the current year instead of hard-coded value.

Automatic Year update in Footer

---

src/components/Contactus.css
src/components/Contactus.js

This PR fixes issue #241
[Informatician.webm](https://github.com/rohansx/informatician/assets/130365071/07ea31bd-8a55-426f-99db-75e763ef609e)
Please review this PR.
Thanks

[Fixed]: change color of submit button, social icons on contact page issue #241

---

src/components/AddBooks/AddBooks.css
src/components/Contactus.css

I have fixed the context overlapping issue and contact us image overflow issue. Kindly check and merge.
**Before fix :**
**After fix:**

fixed content overlapping & contact us image overflow bug. 

---

package-lock.json
src/components/Navbar/NavItems/NavItems.js
src/components/Navbar/Navbar.js

Removed the add book option from navbar, integrated it inside the upload button

Removed the add book option from navbar

---

package-lock.json
src/components/Home/BkCards/CardContent/CardContent.css

Fixes #297 
Removed background color value which is not required in book list.

Fixes CSSValidation errors

---

src/components/Contactus.css
src/components/Contactus.js

* Resolves the issue - #294 
The social icons and the header were not aligned properly... Aligned the same properly and improved the CSS to make the component look better.

Alignment solved on the Contact Us page

---

src/components/faq.css

* Resolves the issue - #311 
The header and the navbar were aligned very close to each other.
Resolved the issue by improving the CSS.

FAQ Header alignment

---

src/components/Footer/Footer.js

* Resolves the issue - #313 
The web page will be redirected to home landing page when the logo/header on the Footer section is clicked.

Added home route redirection on clicking footer logo

---

src/components/AddBooks/AddBooks.css
src/components/AddBooks/AddBooks.js

Changed the Add Book Page UI to match the color scheme of the website.
fixed issue #303

Add book Page UI updated

---

package-lock.json
package.json
src/components/BookList/BookList.js
src/components/Navbar/Navbar.js
src/utils/searchBooks.js

close #259 
https://github.com/rohansx/informatician/assets/115306535/746ce5d2-b043-4545-b5eb-de2933f59aa8

Search functionality Added

---

package-lock.json
package.json
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.js
src/components/Home/CgCards/CgCards.js
src/components/Home/Home.js

Hey @rohansx I have added the category section to the home page. Please review my pr and merge it. Thank you!
- Issue no. #341 
- Screenshot

Added Category section to Home page

---

package-lock.json
package.json
src/components/About/About.js
src/components/About/Testimonial.css
src/components/About/Testimonial.js
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.js
src/components/Home/CgCards/CgCards.js
src/components/Home/Home.js

Hey @rohansx I have added the testimonial section on the About page. Please review my pr and merge it. Thank you!
- Issue no. #339
- Screenshot:-

Added Testimonial section in About Page

---

src/components/faq.css
src/components/faq.js

Resolved Issue #242.  Enhanced faq page UI. 
Preview:
https://github.com/rohansx/informatician/assets/105661636/982301dc-d8dc-4902-89cf-a1d533730545

RESOLVED #242 :  Enhanced the FAQ page

---

src/components/ScrollButton.css
src/components/ScrollButton.js

I have added an animation to the scroll to top button that look pretty attractive as assigned in #352. Kindly check and merge.
Glimpse of the animation added:
https://github.com/rohansx/informatician/assets/103431946/447e9eae-41b3-474c-bcf0-ad7f7a1b183a

Animation added to screen to top button.

---

src/components/ScrollButton.css
src/components/ScrollButton.js

Reverts rohansx/informatician#360

Revert "Animation added to screen to top button."

---

src/components/Home/CgCards/CgCards.js

Previously The Speed of animation of 400 which has now been increased to 1200
The animation is not in sync with other animations due to different number of cards and different width of cards
Issue #365

Category Cards Carousel Speed

---

package-lock.json
src/components/Home/CgCards/CgCards.js

Infinite loop working in category carousel.
Issue #368

Category Cards Carousel Infinite Loop Fixed

---

src/components/Home/CgCards/CgCards.js

Fixed Issue #370

---

src/components/Home/CgCards/CgCards.js

Created a PR that solved issue #373.

Fixed Issue #373 - Dragging Carousel Cards Sometimes Selects Text Instead

---

src/components/Home/CgCards/CardContent/CardContent.js

Merging this PR Closes Issue #372

Fixed #372 - Dragging Category Carousel from images shows buggy behaviour

---

src/components/Error.js

Fixed #386 - Go to Home Page on 404 page should have margin from footer

---

src/components/Footer/Footer.js

Fixed #384 - Go To Top Button Covers Footer Link

---

src/components/Footer/NewsLetter/NewsLetter.css

Fixed #387 - Rounded Corners Removed from Subscribe to NewsLetter

---

src/components/Navbar/Navbar.css

Hamburger menu height issue fixed

---

src/components/Navbar/Navbar.css

Closes #401 
Made changes to the styling to fix the issue.

Fixed issue #401

---

src/components/About/Download.js

* Closes #392 
Added the download button for Google Play Store.

Added G-Play Button for download

---

package-lock.json
package.json
src/components/About/About.js
src/components/About/Download.js
src/components/About/Feature.js
src/components/About/Testimonial.js

* Closes #409 
Added fading animations to the images and the paragraphs such as fade-left for image and fade-right for paragraph.
Also for the testimonials and download section, the animations are added to maintain consistency throughout the web page.
The typo is solved in the features section as mentioned in the issue.

Added fading animations in About Us section + Solved Typo

---

src/components/BookList/BookList.js

Closes #379 
The search book section wasn't aligned properly ,the issue has been fixed now.
before:
after:

Fixed #379 - Search Book section doesn't allign properly

---

src/components/Navbar/Navbar.js

Closes #422 
Top Border Radius of Navbar is now set to zero
Before
After

Fixed #422

---

src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/BkCards/CardContent/CardContent.js

Closes #423 
Things Changed
- Prev and Next Buttons Removed from Library
- New Custom Buttons Implemented using a Ghost Button to use swiper js functionality
- Removed * selector css that was causing design irregularities
- Implemented Tailwind CSS to make sure cards work with custom buttons

Fixed #423 - Previous and Next Buttons Covers Card

---

src/components/Contactus.js

* Closes #391 
The UI of the contact page is improved. Added some styles to the contact form. (Screenshot attached for reference).
Also some fading animations are added to the components as that of about us page.

Improved contact page UI

---

src/components/faq.css

Closes #445 
I have made the FAQ Section responsive.
Please review the code.
Before:
After:

Closes #445

---

src/components/Contactus.css

Closes #444
I have added the minimum height in the contact us form.
Please review the code.
Before:
After:

Closes #444 [Fixed Minimum Height Issue in Contact Form]

---

src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/BkCards/CardContent/CardContent.js

Closes #447 
I have added the hover effect on the book cards. Which shows the despcription of the card.
I have also smoothened the transition as discussed in #447 
Please refer to the latest preview.
Before:
https://github.com/rohansx/informatician/assets/112322302/7b58572c-3a73-4b08-9692-69f1129018d4
After:
https://github.com/rohansx/informatician/assets/112322302/9f5b52c4-2118-4ca6-b13e-d6f9e26ccd45

Closes #447 [Added hover effects to book cards]

---

src/components/About/Download.css
src/components/About/Download.js

Closes #443 
Added Perspective Hover Animation to About Section Image

Fixed #443

---

src/components/About/Testimonial.css
src/components/About/Testimonial.js
src/components/Home/BkCards/BkCards.js

Closes #441 
Added Prev and Next Buttons in testimonial section swiper

Fixed #441

---

package-lock.json
readme.md

made changes in readme file

---

package-lock.json
src/components/Home/BkCards/BkCards.js

Closes #471 
The Home Page UI was stretched. The alignment of the Books Slider is not according the Category Slider.

bug - UI Home page stretched solved

---

CONTRIBUTING.md
package-lock.json

Closes #404 
Made the relevant changes to Contributing.md file keeping in mind the instructions provided.

Updated Contributing.md

---

package-lock.json
src/components/BookList/BookList.js
src/utils/searchBooks.js

Books can not be searched earlier now you can search them easily..
#417 
instead of using the useEffect used a button on which after clicking the request could be sent easily and also there was problem like axios.get was not there also return function doesn't return anything after any result aren't recieved.
#After

Books loading issue resolved

---

src/components/Footer/NewsLetter/NewsLetter.js
src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/BkCards/CardContent/CardContent.js

Closes #480 
The height of the book card was not proper on hover due to animation effect. Also I removed the description in the book card as it was not needed.
Below is my work:
https://drive.google.com/file/d/17-f9_jNLGZgtuOTBXxUIsqaoiI2fth7Z/view?usp=sharing

Bug - Solved the height of the book card not proper on hover

---

src/components/Footer/NewsLetter/NewsLetter.js
src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/BkCards/CardContent/CardContent.js

Reverts rohansx/informatician#483

Revert "Bug - Solved the height of the book card not proper on hover"

---

src/components/Card.css
src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/BkCards/CardContent/CardContent.js

Closes #449
i have modified the cards of books by reducing animation and adding box-shadows ...

Cards modified 

---

src/App.js
src/components/About/About.js
src/components/About/Feature.js
src/components/About/Testimonial.js
src/components/Body.js
src/components/BookList/BookList.js
src/components/Cookie.js
src/components/Footer/Footer.js
src/components/Navbar/NavItems/NavItems.js
src/components/Navbar/Navbar.css
src/components/Navbar/Navbar.js
src/components/PrivacyPolicy.js
src/components/Team/Team.js
src/components/Terms&Service.js
src/components/develop.js

Closes #470 
I have created and added new dark mode feature to all the pages that looks very comfortable to read in night environment.

Dark mode feature added to all pages.

---

src/components/Home/Home.js
src/components/Home/ImgSection/ImgSection.css
src/components/Home/ImgSection/ImgSection.js

Closes #473 
Added typewriter effect to the static start reading text to make it more interactive.

Added typewriter effect to start reading container.

---

package-lock.json
src/components/Navbar/Navbar.js

Fixed the issue #502 . Everything checked and working fine. 
https://github.com/rohansx/informatician/assets/91366697/60452b4c-fac1-41f8-b8a7-5bdab4593709

Issue Fixed

---

package-lock.json
package.json
server/.env
server/.gitignore
server/app.js
server/controller/book.js
server/controller/newsletter.js
server/model/Book.js
server/package-lock.json
server/package.json
server/router/book.js
src/components/AddBooks/AddBooks.css
src/components/AddBooks/AddBooks.js
src/components/AddBooks/Upload.js
src/components/Success.js

upload book functionality added

---

package-lock.json
src/components/Home/BkCards/BkCards.js

Closes #509 
The autoplay was not stopping when the user hovers on the book card in the book slider. I solved this bug.
https://drive.google.com/file/d/1siQRoaVsQn6NO0BfpBALppqVC-KDKKHm/view?usp=sharing

Bug - Autoplay not stopping on hover in book slider solved

---

src/components/Home/SingleBk/SingleBk.js
src/components/Home/SingleBk/SingleBk1.js
src/components/Home/SingleBk/SingleBk2.js
src/components/Home/SingleBk/SingleBk3.js
src/components/Home/SingleBk/SingleBk4.js
src/components/Home/SingleBk/SingleBk5.js
src/components/Home/SingleBk/SingleBk6.js
src/components/Home/SingleBk/SingleBk7.js
src/components/Home/SingleBk/SingleBk8.js
src/components/Home/SingleBk/SingleBk9.js

Closes #521 
Added hover effect and also formatted the whole code

#521 fixed

---

src/components/Body.js
src/components/Categories/biography.js
src/components/Categories/career.js
src/components/Categories/contemporary.js
src/components/Categories/cooking.js
src/components/Categories/garden.js
src/components/Categories/mystery.js
src/components/Categories/politics.js
src/components/Categories/science.js
src/components/Categories/selfhelp.js
src/components/Categories/travel.js
src/components/Home/CgCards/CardContent/CardContent.js

#523 added

---

package-lock.json
src/components/BookList/BookList.css

added new search button with hovering added some css

---

src/components/Cookie.js
src/components/PrivacyPolicy.js
src/components/Terms&Service.js

#540 changed

---

src/components/About/Download.css
src/components/About/Download.js

Closes #511 
Removed spacing on the left of the download button container
| Before | After |
| - | - |
| ![image](https://github.com/rohansx/informatician/assets/57594891/4f78180b-8dd1-4af1-bc5f-ff0330e08e91) | ![image](https://github.com/rohansx/informatician/assets/57594891/5c558b1c-43c4-4006-956a-cf6eba4b4bcd) |

Fixed issue #511

---

src/components/Home/ImgSection/ImgSection.css

Closes #486 
I have made the alignment of the text proper now. Please refer to the latest preview. Also please assign the suitable tags after merging the pull request. 
Before:
After:

Fixed text alignment on the home page [Closes #486]

---

src/components/BookList/BookList.css

Closes #535 
I have fixed the search now it will look good on all devices and made some other things responsive as well.

search-bar-fixed

---

src/components/Navbar/NavItems/NavItems.js
src/components/Navbar/Navbar.css
src/components/Navbar/Navbar.js

Issue No. #492 
I think now the navbar is far better than the previous one and I made bar with pure HTML and CSS.
https://github.com/rohansx/informatician/assets/90946899/337b96d7-6d1d-457c-b271-e02abd0a0916

Enhance Navbar UI #492

---

src/components/Navbar/Navbar.js

Adding prevention function to address this isseu
#564 
#564 
Adding prevention function to address this isseu

Raising this PR for issue #564

---

src/components/Team/ContCard.js
src/components/Team/Contributor.css
src/components/Team/Contributor.js

Closes #554 
In this pr, I Have beautified the contributor's card by adding a view button to be redirected to the users profile with some hover effects and added a border to the individual cards to make them look more prominent.
Further have increased the font size of the title and the number of commits to make it look more prominent.
Before
Updated:

Contributors page beautified.

---

public/index.html

Closes #412
Added loader to the website which displays when the website is loading the content and disappears as soon as it loads the real content of the website.
screenshot
Video
It doesn't look that smooth in video because of the obs studio recorder but in reality it loads really smoothly.
https://github.com/rohansx/informatician/assets/77545230/b9a10f3f-2970-4cf0-b2fb-d4cb3afb025c

Added Website Loader

---

src/components/Contactus.css
src/components/Contactus.js

Enhance contact us

---

src/components/Contactus.css
src/components/Contactus.js

Reverts rohansx/informatician#589

Revert "Enhance contact us"

---

src/components/Body.js
src/components/Copyright/Copyright.css
src/components/Copyright/Copyright.js
src/components/Footer/Footer.js

* Closes #583 
I have added the copyright page to the website with all the necessary content and it works well in both light/dark mode

Added the Copyright page

---

src/components/Accessibility/Accessibility.css
src/components/Accessibility/Accessibility.js
src/components/Body.js
src/components/Footer/Footer.js

* Closes #593 
I have added the accessibility page to the website with all the necessary content and it works well in both light/dark mode

Added the Accessibility page

---

src/components/Navbar/Navbar.js

UI Improvement

---

src/components/Footer/Footer.js

Closes #574 
Added a Dynamic colour change to the links on the footer

Added hover effects to the links in the footer

---

src/components/Body.js

Closes #604 
Hey @rohansx I have added lazy loading to the website. Please review my pr and merge it. Thank you!

Added lazy loading

---

package-lock.json
src/components/BookList/BookList.css

Closes #601 Bug
Simple issue where the text was not visible in dark mode. Added a color property in CSS to fix that.
Before : 
After :

[BUG] Fixed issue #601 which was not showing the text properly

---

src/components/Contactus.css
src/components/Contactus.js

I have improved the UI of the contact us page .Please check and merge my PR.
Kindly inform me if you wanna any other changes.
Closes #531

Contact us page updated

---

src/components/Body.js
src/components/Footer/Footer.js
src/components/Publishers/Publishers.css
src/components/Publishers/Publishers.jsx

* Closes #622 
Added the publishers page with all the necessary content. It works well in both light and dark mode.

Added the Publishers Page

---

src/components/develop.css
src/components/develop.js

* Closes #636 
Solved the issue of dark mode on the Develop page. Now it works correctly on both the themes.
Also the alignment issues were resolved.

Solved the dark mode issue on Develop page

---

src/components/AdChoices/AdChoices.css
src/components/AdChoices/AdChoices.js
src/components/Body.js
src/components/Footer/Footer.js
src/components/Publishers/Publishers.jsx

* Closes #638 
Added the Adchoices page wit appropriate content and linked it with proper routing.
The page works well in both dark and light mode.
Screenshots attached below for reference:

Added the AdChoices page

---

.github/workflows/goosc label.yml
package-lock.json
package.json
src/components/Categories/biography.css
src/components/Categories/biography.js

Closes #570 
designed a page for biography type books while adding books also added show more option if many books are there also made it responsive

#570 page designed

---

src/components/About/About.css
src/components/About/About.js
src/components/About/Feature.css
src/components/About/Feature.js
src/components/About/Testimonial.css
src/components/About/Testimonial.js

Closes #640 
- Updated UI
- Updated Aesthetics

About us enhancement 👍 

---

src/components/About/Testimonial.css
src/components/About/Testimonial.js

Closes #658 
fixed the testimonial and changed the things

#658 fixed

---

src/components/BookList/BookList.css

fixed issue

---

src/components/About/Testimonial.css
src/components/About/Testimonial.js

Closes #665 
making content visible even in dark mode

Fix testimonial 

---

src/App.js
src/components/Body.js
src/components/Bookmarks/BookmarkPage.js
src/components/Home/SingleBk/SingleBk.js
src/components/Home/SingleBk/SingleBk1.js
src/components/Home/SingleBk/SingleBk2.js
src/components/Home/SingleBk/SingleBk3.js
src/components/Home/SingleBk/SingleBk4.js
src/components/Home/SingleBk/SingleBk5.js
src/components/Home/SingleBk/SingleBk6.js
src/components/Home/SingleBk/SingleBk7.js
src/components/Home/SingleBk/SingleBk8.js
src/components/Home/SingleBk/SingleBk9.js
src/components/Navbar/NavItems/NavItems.js
src/context/DataProvider.js

* Closes #666 
Implemented the bookmark functionality in the website. Created a new route '/bookmarks'. When the user clicks on the icon, the books will be stored in the DataContext provided by react and will be maintained through different pages.
Used react hooks and states for this purpose.
Implemented this feature for all the 10 books on the webpage.
[screen-capture (7).webm](https://github.com/rohansx/informatician/assets/113239388/a648691b-29e2-4d44-ac21-db6911d4f3c4)

Added bookmark functionality

---

package-lock.json
package.json
src/components/About/Feature.css
src/components/About/Feature.js

I have updated the Ui of the features section by adding carousel and adding some cool effects .So,please merge and lemme know if you wanna any other changes.
Closes #630

Feature section  UI updated

---

public/sitemap.xml

* Closes #692 
Added the sitemap.xml file which has all the endpoints present in the overall website.
This will enhance search engine optimization (SEO) efforts by improving website visibility and indexing.

Added sitemap.xml for SEO

---

src/components/AddBooks/AddBooks.css
src/components/AddBooks/AddBooks.js
src/components/AddBooks/Upload.css
src/components/AddBooks/Upload.js

I have updated the css for the add book page , kindly check and inform me if you wanna any other changes.
Closes #684
- [ x] My code adheres to the established style guidelines of the project.
- [x ] I have conducted a self-review of my code.

Add book page css modified

---

src/components/BookList/BookList.css

I have modified the css of the books page .kindly check and inform me if you wanna any other changes.
Closes #687

books page css modified

---

src/components/JoinOurTeam/Join.js

UI/UX Improvement

---

src/components/Home/CgCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.js
src/components/Home/CgCards/CgCards.js

I have updated the Ui of the categories section in the home page .Kindly check and inform me if you wanna any other changes.
Closes #686
- [ x] My code adheres to the established style guidelines of the project.
- [x ] I have conducted a self-review of my code.

UI of categories section updated

---

src/components/About/Feature.css
src/components/About/Feature.js
src/components/About/Testimonial.css
src/components/About/Testimonial.js
src/components/BookList/BookList.css
src/components/BookList/BookList.js
src/components/Home/CgCards/CgCards.js

I have  addressed the issue to prevent the new changes from being affected by old changes or modifications made to previous classes.
Closes #721
- [ x] My code adheres to the established style guidelines of the project.

Old changes overlay new.

---

src/components/BookList/BookList.css

Closes #733 
Cards are updated in dark mode
- [ x] My code adheres to the established style guidelines of the project.

cards updated

---

src/components/AddBooks/AddBooks.css

Fixed the icon visibility issue

---

src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/CardContent/CardContent.css

Closes #705 
https://github.com/rohansx/informatician/assets/66116440/c6b913b4-1544-4884-be92-41f68456084f
https://github.com/rohansx/informatician/assets/66116440/25fc968d-2d05-44fd-a2f7-d2b807bf7fd9

added smooth hovering to cards

---

src/components/ScrollButton.css

Added some hover effects to top scroll button

---

src/components/Contactus.css

Added some transition effects on contact us pic

---

src/components/Navbar/NavItems/NavItems.js

Closes #720 
Flixed Upload books icon shrinking on reducing device width.
Before:
After:

navbar upload book icon fixed

---

src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js
src/components/Home/BkCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.js
src/components/Home/CgCards/CgCards.js
src/components/Home/Home.js
src/components/Team/ContCard.js
src/components/Team/Contributor.js
src/components/Team/Team.js

Closes #653 
**Problem:**
In the meet the contributors section, the arrow cursor changes to the hand cursor but as a user it doesn't do anything on clicking which is expected and the view button can't be seen with the next horizontal cards section. I suggest to make the profile pictures clickable as expected and removing the view button, if view button is necessary though, it should be put in a card.
So, I linked the profile picture and added a < HR \/> after the our team intro paragraph for a better UI as I suggested in the issue.

The profile pictures of the contributors are now redirecting to their GitHub pages

---

src/components/Categories/biography.css
src/components/Categories/biography.js
src/components/Home/CgCards/CardContent/CardContent.js

Add Responsiveness to Biography Page

---

public/index.html

* Closes #763
Added proper meta tags for the website. This will improve the website's search engine positioning and increase traffic.

Added proper meta tags 

---

package-lock.json
src/components/AddBooks/AddBooks.css
src/components/AddBooks/AddBooks.js
src/components/AddBooks/Upload.css
src/components/Body.js
src/components/Cards/Card.css
src/components/Home/BkCards/CardContent/CardContent.js

Closes #734 
I have added a dark mode for /addBooks section of the Web App.
I have removed border radius for book image so that is fits the container perfectly.
Review and merge this PR under GSSOC'23
[Screencast from 01-07-23 06:36:03 PM IST.webm](https://github.com/rohansx/informatician/assets/85278243/f3064603-8818-4ab2-868e-e716a65b9898)

Added dark mode for /addBooks page and changes in card border

---

src/components/About/Download.js
src/components/BookList/BookList.js
src/components/Error/Error.js
src/components/FAQ/faq.js
src/components/Home/SingleBk/SingleBk.js
src/components/Home/SingleBk/SingleBk1.js
src/components/Home/SingleBk/SingleBk10.js
src/components/Home/SingleBk/SingleBk11.js
src/components/Home/SingleBk/SingleBk12.js
src/components/Home/SingleBk/SingleBk13.js
src/components/Home/SingleBk/SingleBk14.js
src/components/Home/SingleBk/SingleBk2.js
src/components/Home/SingleBk/SingleBk3.js
src/components/Home/SingleBk/SingleBk4.js
src/components/Home/SingleBk/SingleBk5.js
src/components/Home/SingleBk/SingleBk6.js
src/components/Home/SingleBk/SingleBk7.js
src/components/Home/SingleBk/SingleBk8.js
src/components/Home/SingleBk/SingleBk9.js
src/components/Navbar/NavItems/NavItems.js
src/components/Team/Team.js
src/pages/About/About.js
src/pages/Awards/BookAwards.js
src/pages/Benefits/Benefits.js
src/pages/BookFormats/BookFormats.js
src/pages/Bookmarks/BookmarkPage.js
src/pages/Contact/Contactus.js
src/pages/Develop/develop.js
src/pages/GenreDetails/GenreDetails.js
src/pages/JoinOurTeam/Join.js

Closes #719 
Added proper alt attributes to all the img tags

Proper alt attribute added

---

src/app/layout.js
src/components/Client.js
src/components/Footer/Footer.css
src/components/Footer/Footer.js
src/components/Footer/NewsLetter/NewsLetter.css
src/components/Footer/NewsLetter/NewsLetter.js
src/components/Navbar/Navbar.js

For #659 
Adding footer and newsletter

implementing footer and newsletter

---

package-lock.json
src/components/About/Contributors.js
src/pages/About/About.js

Added contributors list in about page

---

src/components/Footer/Footer.js
src/components/Footer/NewsLetter/NewsLetter.css
src/components/Footer/NewsLetter/NewsLetter.js

Closes #607 
Added the subscribe to newsletter below the Informatician logo

Added Newsletter below the logo

---

Added more features

Added more features

---

src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js

Closes #782  **Error in SlideBar**
Did changes in some CSS to fix the sidebar and remove unnecessary style properties.
https://github.com/rohansx/informatician/assets/86224794/271358d1-82c1-4b79-ab5f-92c1c2656dcc

Fix SlideBars

---

src/components/Footer/Footer.css
src/components/Footer/NewsLetter/NewsLetter.css
src/components/Footer/NewsLetter/NewsLetter.js

#788
The enhancement of  the hover effect in the footer section is successfully done
-Added left-to-right underline animation
-Edit the styling of the newsletter section for light and dark theme
-Added a more readable placeholder
https://github.com/rohansx/informatician/assets/83147410/b25b18a8-5a08-425c-a3bf-99fad85ce177

hover effect enhancement done in the footer section

---

src/components/About/Feature.css

Solved Features Card Responsive & Overflowing issue for all devices  #814 
Before it looks like this:
[screencast-localhost_3000-2023.07.03-21_37_38.webm](https://github.com/rohansx/informatician/assets/106610322/4e099121-9211-42b8-9f57-7863bf081d94)
Now After Solving the responsive issue:
[screencast-localhost_3000-2023.07.04-22_50_33.webm](https://github.com/rohansx/informatician/assets/106610322/f54e27fb-90e4-4c34-839d-be06c0d7b8f8)

Solved Features Card Responsive & Overflowing issue for all devices 

---

src/components/About/Download.js

Closes #822 
Alignment of download buttons have been fixed

Alignment of download buttons have been fixed

---

src/components/Footer/NewsLetter/NewsLetter.js
src/components/Newsletter.js
src/pages/Contact/Contactus.js

* Closes #784
Added toast errors for success and errors with their respective styles instead of simple javascript alerts to enhance the UI.

added toast errors

---

app/about/About.css
app/about/page.jsx
app/layout.jsx
components/About/Download.css
components/About/Download.js
components/About/Feature.css
components/About/Feature.js
components/About/Testimonial.css
components/About/Testimonial.js
components/Footer/NewsLetter/NewsLetter.css
components/Footer/NewsLetter/NewsLetter.js
components/ScrollButton/ScrollButton.css
components/ScrollButton/ScrollButton.js

For #659 
Adding about page
Link: https://informatician-git-about-s2sharpit.vercel.app/about

adding about page in website

---

src/components/Home/BkCards/BkCards.js
src/components/Home/BkCards/Books.js

Closes #803 **Code Refactor of BkCards Component**
Removed Repeated codes

bkCards Code Refactor

---

app/contact/page.jsx

fixing errors in contact page and optimizing it
Link: https://informatician-git-contact-s2sharpit.vercel.app/
Error:

fixing errors in contact page and optimizing it

---

.github/workflows/lock.yml

Closes #836 
This repository contains a workflow called lock.yml in the .github/workflows directory. The workflow is designed to reduce notifications when a maintainer adds a label and allows for conversation unlocking until it is locked again.

feat : Create Lock.yml ✔

---

src/components/Footer/Footer.js
src/components/Home/CgCards/CardContent/CardContent.css
src/components/Home/CgCards/CardContent/CardContent.js

Closes #837 
Hover effect of Github logo has been updated.

Hover effect of Github logo has been updated

---

package-lock.json
package.json
public/index.html
src/components/Body.js
src/components/Loader/loader.css
src/components/Loader/loader.js

Fixed the loader page not working properly
Closes #844 
- Remove code from html page
- Design a new component loader 
- fixed the suspense fallback
- Maintain a stable corte js version

Added the file and fixed the loading issue in server side componets

---

server/app.js
server/package-lock.json
server/package.json
src/components/Newsletter.js

* Closes #774 
* PR conflicts #819

mail functionality - PR conflicts #819, issue #774

---

app/accessibility/Accessibility.css
app/accessibility/page.js

adding accessibility page

---

.eslintrc.json
components/Hero/Hero.jsx
package-lock.json
package.json

Fixing All issues by adding eslint config #659

Fixing All issues by adding eslint config

---

app/awards/BookAwards.css
app/awards/page.js

adding awards page

---

app/formats/BookFormats.css
app/formats/page.js

adding book-format page

---

app/cookie/Cookie.css
app/cookie/page.js

Closes #659 
link: https://informatician-git-cookie-s2sharpit.vercel.app/cookie

adding cookie policy page

---

.eslintrc.json
app/addBooks/page.jsx
components/Hero/Hero.jsx
components/Upload/Upload.js
package-lock.json
package.json
styles/AddBooks.module.css
styles/Upload.module.css

Added New addBooks Page also added Books Upload Component with Style Files #659

Added New addBooks Page also added Books Upload Component with Style Files

---

app/copyright/Copyright.css
app/copyright/page.js

For #659 
link: https://informatician-git-copyright-s2sharpit.vercel.app/copyright

adding copyright page

---

app/genre/GenreDetails.css
app/genre/page.js

For #659 
link: https://informatician-git-genre-s2sharpit.vercel.app/genre

adding genre details page

---

app/privacy/PrivacyPolicy.css
app/privacy/page.js

For #659 
link: https://informatician-git-privacy-s2sharpit.vercel.app/privacy

adding privacy policy page

---

app/publishers/Publishers.css
app/publishers/page.jsx

For #659 
link: https://informatician-git-publishers-s2sharpit.vercel.app/publishers

adding publishers page for nextjs

---

src/components/Footer/Footer.css
src/components/Footer/Footer.js
src/components/Footer/NewsLetter/NewsLetter.css
src/components/Footer/NewsLetter/NewsLetter.js
src/utils/searchBooks.js

Closes Issue: #897 
As mentioned, I have redesigned the new newsletter section, while also fixing the old logic to get user email from the component and pass it on to the backend. Also, I have fixed the codebase of footer section so that it is easier to keep track of the items and links.
Also, A redesigned css for both newsletter and footer to support responsive designing.
Before:
After:

Fix: Navbar

---

src/components/Categories/biography.js
src/components/Categories/career.js
src/components/Categories/component/Card.js
src/components/Categories/contemporary.js
src/components/Categories/cooking.js
src/components/Categories/garden.js
src/components/Categories/index.css
src/components/Categories/mystery.js
src/components/Categories/politics.js
src/components/Categories/science.js
src/components/Categories/selfhelp.js
src/components/Categories/travel.js

#826 
I have added content for all the genres, and made the UI of the content card better. Because the genre section was only directing to the biography page, i have taken screenshots from that biography.js only, but have updated the content of all genres on their respective pages only.
I have checked in black mode as well, also fitted it in mobile view.

Content of all the genres

---

app/terms/TermsAndService.css
app/terms/page.js

For #659 
link: https://informatician-git-terms-s2sharpit.vercel.app/terms

adding terms page

---

app/faq/faq.css
app/faq/page.js

For #659 
link: https://informatician-git-faq-s2sharpit.vercel.app/faq

adding faq page

---

src/components/Home/BkCards/BkCards.css
src/components/Home/BkCards/BkCards.js
src/components/Home/CgCards/CgCards.js
src/components/Home/Home.js

#858
Closes #858 
Changed font color of titles on Home page for light and dark theme

changed color of headings on home page

---

readme.md

Update readme.md with website link

---

src/components/About/Testimonial.css
src/components/About/Testimonial.js
src/pages/About/About.js

#889 
Ui of the core team members cards is improved on the About page.

Core team UI improvement

---

server/middleware/auth.middlware.js
server/package-lock.json
server/package.json
server/router/book.js
server/router/contact.js
server/router/newsletter.js

Server side middleware is added

---

src/components/About/Contributors.js
src/components/AddBooks/Upload.js
src/components/Home/BookComponent/BookComponent.css

#885 
Updated the headings on all the pages.

Made headings visible

---

src/pages/Contact/Contactus.js

Closes #899 
Added all necessary ARIA attributes which enhance the accessibility of the contact us form.

Added ARIA attributes to contact us form

---

src/pages/Accessibility/Accessibility.css
src/pages/AdChoices/AdChoices.css
src/pages/Cookies/Cookie.css
src/pages/Copyright/Copyright.css
src/pages/Privacy/PrivacyPolicy.css
src/pages/Publishers/Publishers.css
src/pages/Terms/TermsAndService.css

Pages styles aesthetic

---

app/api/book/[id]/route.js
app/api/book/category/route.js
app/api/book/new/route.js
app/api/book/route.js

For #659 
fixing importing error:
fixing category TypeError:

Fixing 2 errors in backend

---

src/components/About/Feature.css
src/components/About/Feature.js

#886 
I have improved the Ui of the features cards and made the arrows visible in the dark/light mode.

Features Cards Ui

---

src/components/Navbar/NavItems/NavItems.js
src/components/Navbar/Navbar.js

Alignment Issue with navbar #921

css Fix for navbar bug no :- 921

---

src/components/About/Download.js
src/components/About/Feature.js
src/pages/About/About.js

Closes #905 
Font color of Headings have been changed

Font color of the Heading have been changed

---

src/components/BookList/BookCard.css
src/components/BookList/BookCard.js
src/components/BookList/BookList.css
src/components/BookList/BookList.js

[BUG] Search bar is not working #741
Closes #741
The search feature in the books page is not working so added it.  The details are displayed using the data available in books.js file.  We can search for title, author and ISBN number in the search box and the result of this search is displayed below. If no result is obtained then the "No results found" text is displayed below.
https://github.com/rohansx/informatician/assets/95839946/afdfe837-4ea9-4953-9a88-d6be9ec0c758
-  [x] My code adheres to the established style guidelines of the project.

Added Search Functionality to Books Page

---

src/components/Footer/NewsLetter/NewsLetter.css
src/components/Footer/NewsLetter/NewsLetter.js

Closes #860 
Enhanced the UI of the Newsletter Subscription section on books page.
- `src/components/Footer/NewsLetter/NewsLetter.css`
- `src/components/Footer/NewsLetter/NewsLetter.js`
[Informatician.webm](https://github.com/rohansx/informatician/assets/130365071/fbfd0fee-9378-48cd-b6f9-bbd1928a00af)

style: enhance UI of newsletter subscription

---

src/components/Body.js

I have fixed the page not scrolling to top issue and made pages to auto scroll to top whenever user changes the route.

Fixes: pages not auto scrolling to top issue

---

src/components/Home/CgCards/CardContent/CardContent.js
src/components/Home/CgCards/CgCards.js

Closes #949 
Earlier the categories cards were only routing to the biography page now the improved routing properly routes to the categories page clicked.
https://github.com/rohansx/informatician/assets/79076050/c00ec44a-f2ed-4fc4-8ba0-3f12eafd35c4

Proper Routing of categories

---

src/components/About/Feature.css
src/components/About/Feature.js

Core team UI improvement
Closes #959

Code opimization in features 

---

server/model/Book.js
server/model/newsletter.js

Server side validation is done

---

src/components/BookList/BookData.js
src/components/BookList/BookList.js

#928 
Mapped the quotes content in the BookData.js (reduced the codelength by a massive 33%)

Mapped the content of Quotes

---

src/components/Footer/Footer.js
src/components/Navbar/NavItems/NavItems.js
src/components/Navbar/Navbar.js

Closes #940 
- Successfully made all the footer buttons scroll to top top on clicking.
- Made the github button open the link in new tab & Twitter/Discord buttons now point to the Under Development Page alongwith scrolling to the top.
- Made the navbar button scroll to top as well.
- Made the Informatician Logo scroll to top as well.

Made Footer & Navar buttons Scroll To Top & Minor Changes 

---

src/components/BookList/BookList.js

Closes #943 
The `BookList.js ` file is updated and in the quotes section `copy to clipboard` functionality is added, which would help the user to copy the quotes and use them at his/her convenience.
A copy to clipboard icon is added as below:

[UPDATE] Copy to Clipboard feature Added to Quotes Section

---

server/app.js
server/model/Book.js
server/package-lock.json
server/package.json
server/router/book.js
server/router/contact.js
server/router/newsletter.js

Closes #1013 
Added the missing package called **validator**.
**Also, I Fixed codes in different files of the server folder that causes errors while running the server**

Server code fix

---

src/components/BookList/BookData.js
src/components/BookList/BookList.js

conflics are resolved

---

src/components/Home/BkCards/BkCards.js
src/pages/Login/Login.jsx
src/pages/SignUp/SignUp.jsx
src/utils/validation.js

Closes #1015 **[Feature] Add Inline validation in login and Signup**
Added inline validation in login and signup and prevent requests with invalid data.
https://github.com/rohansx/informatician/assets/86224794/4345c865-5fc5-459e-8fe1-c90806a63d02
@crocmons You are right, the issue #1021 **[Styles]: Login and Signup page responsiveness** is invalid cause it's alraedy responsive. In the local environment, the page is not responsive due to some unknown reason but in deployment, it looks perfect. I apologize for the inconvenience you can close issue #1021. I was unable to message on that issue comment box due to the locked conversation so I messaged here.
Thanks :)

Inline validation in login/signup

---

src/components/About/Contributor.css
src/components/About/Contributors.js

Closes #807 
Added carousel to the contributors section of the about page.
https://www.loom.com/share/f5a05c6916db467390f37dfe98aecb2b?sid=f1e81d06-ff2c-45f7-b8e1-5a14713c7fcd
[Video Preview]
- [] My changes have not introduced any new warnings.
Add  "npm install react-slick slick-carousel" to package json to make it work!

added carousel

---

src/pages/Login/Login.jsx
src/pages/SignUp/SignUp.jsx

Closes #1022 **[Feature] Show password Funtionality**
Added show password functionality in login and signup
https://github.com/rohansx/informatician/assets/86224794/53aee7d9-efd9-4d1f-b5b2-a88276e51a71

Add show password Functionality

---

package-lock.json
package.json
server/app.js
server/router/book.js
src/components/About/Contributors.js
src/components/Navbar/Navbar.js
src/utils/searchBooks.js

Closes #988
This pull request adds book search functionality to the homepage of the application, allowing users to search for books and receive book suggestions based on their query. Additionally, it fixes the issue with the environment variable for the Google Books API key.
**Changes Made:**
1. Added book search functionality to the homepage, including:
- Created a new `searchBooks` function in the `utils/searchBooks.js` file to fetch book data from the Google Books API based on user query.
- Implemented the search functionality in the `Navbar` component.
- Displayed search results with book covers, titles, and authors.
- Limited the search results to show a maximum of 5 books.
2. Fixed the environment variable for the Google Books API key, ensuring it is correctly sourced and available …

 Add Book Search Functionality and Fix Google Books API Key

---

server/router/contact.js
src/components/About/Contributors.js
src/pages/Contact/Contactus.js

Closes #986
This pull request introduces a new feature that enables the sending of emails from the contact form using Nodemailer. It enhances the existing contact form functionality by integrating Nodemailer to handle email transmission, providing users with a seamless way to get in touch with us.
Changes in this pull request include:
- Added Nodemailer package to the project dependencies.
- Implemented a new email sending function that utilizes Nodemailer to send messages from the contact form.
- Configured the email settings, including SMTP details and sender information, for the Nodemailer integration.
- Enhanced form validation and error handling for a smooth user experience.
- Updated the user interface to provide feedback when the email is successfully sent. …

Added Sending email From contact Form

---

src/components/Home/ImgSection/ImgSection.js

Closes #1035 
Original:
Updated:

fixed positioning in mobile screen

---

.github/workflows/codeql.yml
.github/workflows/greetings.yml

Add-codeql-greetings-file #659 
Before:
After updating file:

Add-codeql-greetings-file in Next.js 13

---

package-lock.json
package.json
src/components/About/Contributor.css
src/components/About/Contributors.js

#1042 Contributors visibility
Closes #1042 
Fixed the bug contributor visibility.

contributor visibility

---

src/components/BookList/BookList.css
src/components/BookList/BookList.js

Add responsiveness on book page

---

src/pages/Terms/Terms&Service.js
src/pages/Terms/TermsAndService.css

Closes #1047 
- **JavaScript Changes:**
- Added `role="main"` to the main content container to indicate the main content of the page for better accessibility.
- Changed the heading element from `<h2>` to `<h1>` for improved semantic structure and added an `id` attribute for association with `section` element which contains multiple `p` element in it. This helps us the accessibility devices to properly announce the content to the end user.
- Added `aria-labelledby` attribute to the content section to establish a relationship with the heading for better screen reader navigation.
- Added `role="list"` to the unordered list and `role="listitem"` to list items to convey the list structure to assistive technologies.
- Improved the `aria-live` and `aria-describedby` attributes for the contact …

feat: made entire terms and services page accessible 🚀

---

server/controller/book.js
server/model/Book.js
server/model/newsletter.js
src/components/AddBooks/AddBooks.js
src/components/AddBooks/Upload.js
src/components/Footer/NewsLetter/NewsLetter.js
src/utils/impURLs.js

Closes #946
**Book can be added multiple times (Duplicate data)** 
Added code in the backend to prevent adding book that is already present in the database
Added a new file to switch between the local backend URL and hosted backend URL.
https://github.com/rohansx/informatician/assets/86224794/9e0efaa7-5a82-4f0a-8222-004af4c9b1e6
- [x My code adheres to the established style guidelines of the project.

Prevent Storing of Duplicate Books

---

src/components/FAQ/faq.js
src/components/FAQ/faqData.js

Closes #1057  **[Change] Faq component reusable code**
Added reusable code in the Faq component and decreased repetition.
**Before**
**After**

FAQ Reusable Code

---

components/Footer/Footer.css
components/Footer/Footer.js
components/Footer/NewsLetter/NewsLetter.css
components/Footer/NewsLetter/NewsLetter.js
next.config.js
utils/Constants.js

Added updated Newsletter, Footer & Constant File #659

Added updated Newsletter, Footer & Constant File

---

server/app.js
server/package-lock.json
server/package.json
server/router/book.js

Closes #1028 
Implementation of Swagger API for better testing.

Configuring Swagger API into the application

---

server/middleware/auth.middlware.js
server/router/contact.js
server/router/newsletter.js
src/components/AddBooks/AddBooks.js
src/components/AddBooks/Upload.js
src/components/temp.js

closes #1059
Improved the code of the middleware and add the response handling in all the Axios request route that uses the middleware.
https://github.com/rohansx/informatician/assets/86224794/a2c7dd97-7ae1-4df7-8c92-572441d75401

Middleware handling

---

src/components/Body.js
src/components/Home/BookComponent/GoogleBookComponent.js
src/components/Home/Bookpreview/BookPreview.js
src/components/Navbar/Navbar.js

Closes #1049
📚 This PR proposes the implementation of the Google Book Viewer integration as an enhancement to the Informaticon website. The integration enables users to read e-books directly on the website, providing a seamless reading experience and eliminating the need for external applications or devices.
Key Features:
🖼️ Integrated Google Book Viewer to display e-books on the website.
📖 Supports various formats, including PDF and EPUB, to cater to a wide range of e-books.
😊 User-friendly interface for easy navigation and reading.
🔍 Allows users to zoom in/out and navigate pages for comfortable reading.
📱 Responsive design ensures compatibility with different screen sizes and devices.
Additionally, I've ensured that when a user clicks on a book after searching, it opens the book detail …

📚 Google Book Viewer Integration for Enhanced Informaticon Website 📘🌐

---

src/components/AddBooks/AddBooks.css
src/components/AddBooks/AddBooks.js
src/components/AddBooks/Upload.css
src/components/AddBooks/Upload.js

Closes #1056 
**Feature] Same form inserting book data and uploading book**
Add a single functional form for storing book pdf and book data.
https://github.com/rohansx/informatician/assets/86224794/78c9940b-4ffd-4ebe-bef0-b4220a26ad1c

Add book form Enhancement

---

src/pages/Accessibility/Accessibility.css
src/pages/Accessibility/Accessibility.js

Closes #994 
Made the entire accessibility section into an accordion for better experience and better utilization of space

Made accordion out of the accessibility links

---

.gitignore

Updating gitignore file to ignore .next and other folders which shouldn't be added to repository

updaing .gitignore file

---

app/layout.jsx
utils/Books.js

Fixed error in displaying book section on home page.

fixing bugs

---

readme.md

Updating "How to Install it?" section in Readme.md

Updating "How to Install it?" section in Readme.md

---

components/Footer/Footer.js

Closes #1105 
I have fixed the padding in footer section so it not touches the edges of window and mobile screens

fixes padding issue in footer

---

app/addBooks/page.jsx

Closes #1083 
Currently users can select negative numbers for the number of pages
this is to fix this bug and
allow only positive numbers while taking input from users for number of pages while adding book.
But pr has code which fixes that bug.

fix: fixes issue #1083

---

components/Footer/Footer.js

Close #1094 
- Fixed the Logo image blending issue with the background color of the Footer component
|BEFORE|AFTER|
|:----:|:----:|
|![](https://user-images.githubusercontent.com/92252895/256303183-0aeb7a99-8ddf-437c-b343-bb17c0f786bf.png) | ![](https://user-images.githubusercontent.com/92252895/256303218-a635bf46-db77-428b-8118-45e3c9461a67.png) |

fix: improper footer logo blending with background 🛠

---

app/login/page.jsx

Close #1124 
- Fixed the invisible text on input fields for Login page during Dark Mode by adding explicit colors with tailwind classes.
|BEFORE|AFTER|
|:---:|:---:|
| ![before](https://github.com/rohansx/informatician/assets/92252895/2f8ef414-d5d3-4e2e-8c27-55afe75c868e) | ![after](https://github.com/rohansx/informatician/assets/92252895/b8eef196-fe07-4fff-af3a-a67448ea21e5) |

fix: invisible text on input field during dark mode on login page 🛠️

---

app/books/page.jsx

Close #1123 
- Revamped the Quotes blocks with best style practices
- Improved the copy quote feature by removing the event from quote and then added the event to the clipboard image.
- Made the copy quote feature accessible by adding proper `aria-label`.
- Additionally, i formatted to code to maintain code consistency.
|||
|:---:|:----:|
|**BEFORE**| ![image](https://github.com/rohansx/informatician/assets/92252895/b736392c-8e6d-495b-9d87-2f2b657ada37) |
|**AFTER**| ![image](https://github.com/rohansx/informatician/assets/92252895/adbacfb4-55a5-459c-9972-b46389500359) |

feat: revamp quotes section and improved copy quote feature 🚀✨

---

components/Footer/Footer.css
components/Footer/Footer.js

Closes #1118
- **Added required changes in Footer.js and Footer.css Files to Resolve Poor Footer UI**

fix: Update Footer UI in Footer Section

---

app/login/page.jsx
app/signup/page.jsx

Closes #1103
**[Feature] Add show password**
Added show password icon and it's functionality
https://github.com/rohansx/informatician/assets/86224794/9dc3820c-c0fc-4d99-b7a8-246946149753

Show password Functionality

---

app/layout.jsx
components/Preloader/Preloader.css
components/Preloader/Preloader.jsx

Closes #1091 
Added Preloader animation.
- `app/layout.jsx`
- `components/Preloader/Preloader.jsx`
- `components/Preloader/Preloader.css`
[localhost-3000.webm](https://github.com/rohansx/informatician/assets/130365071/f1c47fdb-35c4-43fe-be54-71d83624bc63)

feat: add pre-loader animation

---

app/addBooks/page.jsx
app/books/page.jsx
app/contact/page.jsx
app/login/page.jsx
app/signup/page.jsx
app/team/Contributors.js
components/Footer/Footer.js
components/Footer/NewsLetter/NewsLetter.js
components/Navbar/NavItems/NavItems.js
components/Upload/Upload.js

Closes #1119 
- Added `aria-label in app-->addBooks-->page.jsx File`
- Added `aria-label in app-->books-->page.jsx File`
- Added `aria-label, title, rel to Social Icons and specifically aria-label added to Submit Accessing Button in app-->contact-->page.jsx File`
- Added `alt text to Login Image Element and aria-label , aria-labelledby attributes to Form Section in app-->login-->login.jsx File`
- Added `alt text to Signup Image and aria-label attribute to Form Section in app-->signup-->signup.jsx File`
- Added `aria-label, target, title attributes to GitHub Social Link in app-->team-->Contributors.js File`
- Added `aria-label, target, title, rel attributes to 3 Social Links in components-->Footer-->Footer.js File`
- Added `aria-label attribute to Form Section in …

fix: aria-label, title, rel, target for Social Icons in Footer Section and Other Minor Bugs in Some Pages

---

components/Home/CgCards/CgCards.js

Closes #1121 
Fixed bug: log messages on browser's console.
- `components/Home/CgCards/CgCards.js`
[localhost-3000.webm](https://github.com/rohansx/informatician/assets/130365071/35916a7e-7475-4cc4-9697-c4955d22377a)

fix bug: display log messages on browser's console

---

app/addBooks/page.jsx
app/login/page.jsx
app/signup/page.jsx
components/Upload/Upload.js
utils/validation.js

Closes #1110  **[BUG] All form validations lost due to migration**
Added inline validation in **signup, login, and addbook forms**
https://github.com/rohansx/informatician/assets/86224794/a70607f9-4e13-46d9-815f-f9b8263e81de

Validation in All forms

---

components/Footer/NewsLetter/NewsLetter.js
package-lock.json

##remove spamming from submit button of newsletter and if error occurs then submit button is not disabled
Closes #1143 
I have solved 2 problems-
1.bug of spamming of submit button is removed
2.if any error occur while subscribing, the subscribe button will not be disabled, letting user to try again more
https://github.com/rohansx/informatician/assets/97560633/2e6d59d5-b6c8-49fe-8c1c-6d2d31945101

updated newsletter submission

---

components/Home/ImgSection/ImgSection.js
package-lock.json

fixed issue 1140 : Inconsistent Casing

---

app/books/page.jsx
next.config.js
public/search-svgrepo-com.svg

Closes #1135 
- [] I have included comments in areas that may be difficult to understand.

Search Icon Not Properly Aligned #1135

---

app/login/page.jsx

Closes #1159
This pull request addresses the issue where the font color for the email and password input fields was not properly visible, making it challenging for users to enter their credentials. The changes in this pull request improve the readability of the input fields by adjusting the font color, ensuring better visibility for users.
**Changes Made:**
1. Modified the CSS styles for the email and password input fields.
2. Updated the font color to a more contrasting and readable color.
**Before Changes:**
Before the changes, the font color for the email and password input fields was set to a low-contrast color, making it difficult for users to see what they were typing.
**After Changes:**
With the changes introduced in this pull request, the font color for the email and password …

Fixed Font Color for Email and Password Input Fields

---

components/Footer/Footer.js

Closes #1171
- Fixed the lacking of proper padding for Footer component on Mobile devices.
|BEFORE|AFTER|
|:----:|:----:|
|![before](https://github.com/rohansx/informatician/assets/92252895/f03ef7e3-ee76-4c5d-94f9-2089c615820f)|![after](https://github.com/rohansx/informatician/assets/92252895/a487f702-7554-42da-a389-f34ef0bd3292)|

fix: lack of paddings for footer on mobile devices ⚒️

---

app/api/auth/[...nextauth]/route.js
app/api/register/route.jsx
libs/prismadb.jsx
prisma/schema.prisma

Added NextAuth API Routes & PrismaDB

Added NextAuth API Routes & PrismaDB

---

app/books/Spinner.css
app/books/page.jsx
components/Quotes/Card.jsx
model/User.js
package-lock.json
package.json

Closes #1155
This PR addresses the current limitation of hardcoded quotes on our website by proposing the integration of a dynamic API that fetches real-time quotes from famous authors. By implementing this API integration, we aim to enrich the user experience and offer a diverse range of inspirational content. 🌟📚
Key Features Implemented:
🔌 API Integration: I have successfully implemented a dynamic API connection that fetches famous quotes from renowned authors in real-time.
🎯 Diverse Categories: Users can now explore various categories of quotes, allowing them to find inspiration on different themes and topics.
https://github.com/rohansx/informatician/assets/85815172/32802e15-92d8-4d9e-b718-45b75f636c87

🚀 Dynamic Famous Quotes Integration - Inspire and Motivate Users 🔧💬

---

app/books/page.jsx
components/Quotes/Card.jsx
package-lock.json

Closes #1176 
I have improved styling of the quotes section

improved quote section

---

components/Upload/Upload.js

Closes #1133
**[Feature] Cross icon for removing selected book**
Added a cross icon to remove selected books.
https://github.com/rohansx/informatician/assets/86224794/a483a9de-ae06-405a-9604-afc690f64951

Upload book cross icon

---

app/api/auth/[...nextauth]/route.js
app/api/register/route.js
app/login/page.jsx
app/signup/page.jsx
components/Navbar/NavItems/NavItems.js
components/Navbar/Navbar.js
package-lock.json
package.json
utils/database.js

Full functional Next Auth authentication has been added.
[screencast-localhost_3000-2023.08.02-23_34_36.webm](https://github.com/rohansx/informatician/assets/106610322/90a102f1-23d2-463d-8ce8-ca25be14f130)

Added Fully Functional NextAuth Authentication

---

components/About/Testimonial.js

Closes #1175 
Hey @rohansx I have added Twitter URLs to the testimonials section so that users can see the details of the admins and mentors.

Added twitter to the testimonials section

---

app/bookmark/page.jsx
app/books/page.jsx
app/googlebooks/[bookId]/[isbn]/page.jsx
components/TNYCards/BkCards.js
package-lock.json

Closes #1205 
- Added the bookmark feature with json data present in the same file.
- Also added the feature of removing the bookmark by using useState Hook to remove bookmark books (asynchronously just on page).
**1. **Changes:****
**2. **Remove button feature:****

Added new feature of bookmark with useState for remove button

---

components/Navbar/Navbar.js
package.json
vercel.json

Solved Vercel Prisma Deployment Issue
Before-
After Solving the issue:

Solved Vercel Prisma Deployment Issue

---

components/Footer/NewsLetter/NewsLetter.css

Closes #1194
This pull request contains the modified code for the "Addition of Hover Effect on Subscribe button". It is the result of following issue:
_Addition of Hover Effect on Subscribe button_

Addition of Hover Effect on Subscribe button

---

components/Navbar/Navbar.css

Align the underline in the middle in navbar

---

.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/styles.yml

Closes : #1183 
- ` Added styles.yml File for Raising Enhancement Requests in Issue Templates.`
- `Added documentation.yml File for raising Documentation related Requests in Issue Templates.
`

fix: Added styles.yml , documentation.yml Files for Issue Templates

---

app/layout.jsx
app/page.jsx
components/Footer/Footer.js
components/Footer/NewsLetter/NewsLetter.css
package-lock.json

Closes #1158
When enabling dark mode in the application, the Newsletter component fails to adopt the dark mode theme Now I  Have fixed this issue I have removed the background color which is cause for dark mode issue which is now solved :)

Dark Mode is now Applied to Newsletter Component ✨

---

package-lock.json
package.json

For #659 
installing required packages to fix package not found error

fixing package not found error

---

app/formats/page.js
components/Navbar/NavItems/NavItems.js

For #659 issue_number
|      Original       |      Updated       |
| :-----------------: | :----------------: |
| ![image](https://github.com/rohansx/informatician/assets/104740281/205ba1c2-b131-47cb-b8a8-3c72c4eece3d) | ![image](https://github.com/rohansx/informatician/assets/104740281/25b1d028-01e5-44bf-8f99-8acaebf47d5a) |

removing bg-white for better ui in dark mode

---

.github/PULL_REQUEST_TEMPLATE.md

Updating the screenshot section in the PR template to showcase the latest changes, enabling maintainers to easily compare the original and updated versions side by side.

updating screenshot section in PR template

---

app/login/Login.jsx
package-lock.json

Closes #1241
This pull request addresses two issues in the `Login` component:
1. Corrected the placement of `onClick={login}` in the login form. Previously, the `onClick` event was erroneously placed on the form tag, causing validation to trigger on any form element change. I've moved the `onClick` event to the login button to ensure it triggers only when the login button is clicked.
2. Added a password visibility toggle feature to the password input field. I've implemented an eye icon that toggles between showing and hiding the password text when clicked. The icon changes color and the password visibility changes accordingly.
This fixes the issue of validation errors appearing without submitting the form and enhances the user experience by providing a password visibility toggle feature. …

FIxed form errors and eye icon

---

app/about/page.jsx
app/accessibility/page.jsx
app/adchoices/page.jsx
app/addBooks/AddBooks.jsx
app/addBooks/page.jsx
app/awards/page.js
app/benefits/page.js
app/bookmark/page.jsx
app/books/[id]/page.jsx
app/books/page.jsx
app/contact/page.jsx
app/cookie/page.js
app/copyright/page.js
app/develop/page.jsx
app/faq/page.js
app/formats/page.js
app/genre/page.js
app/join/page.js
app/login/page.jsx
app/metadata.js
app/pcategories/biography/page.js
app/privacy/page.js
app/publishers/page.jsx
app/signup/page.jsx
app/team/page.jsx
app/terms/page.js

For #659 
This pull request aims to enhance the user experience and maintain consistent branding by dynamically updating the page titles across the website. Currently, the homepage title is set as "Informatician," but when users navigate to other pages, the title remains the same, lacking the necessary context.
With this pull request, we propose the following changes to the website's page titles:
1. **Homepage Title**: The homepage title will remain as "Informatician."
2. **Page Navigation Titles**: When users navigate to other pages, the page title will follow the format "<page title> - Informatician." This will provide clear identification of the current page and reinforce the website's branding.
1. **Improved User Experience**: Dynamic page titles will give users a clear understanding …

Dynamic Page Titles for Improved User Experience and Branding

---

components/Footer/NewsLetter/NewsLetter.css
components/Quotes/Card.jsx
styles/globals.css

Closes #1195
This pull request contains the updated code for 'Quote Section Content Position Correction'. It is the result of following issue:
**Quote Section Content Position Correction**

Quote Section Content Position Correction

---

components/Footer/NewsLetter/NewsLetter.css

Highlighted button text

---

app/addBooks/AddBooks.jsx
components/Upload/Upload.js
model/Book.js

Closes #1166
**Change add book form Book image URL field type text to file**
Change the book image type to file from text. 
https://github.com/rohansx/informatician/assets/86224794/ba06e85f-66f3-49f1-bd56-e4207ea3789a

Book image type to image

---

app/faq/Accordion.jsx

Closes #1274 
|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

#1274 fixed

---

app/addBooks/AddBooks.jsx

Closes #1264 
**Add preview image functionality in the add book image upload field**
Added a preview image functionality for Add book cover page image field.
https://github.com/rohansx/informatician/assets/86224794/9ca9c4a2-34f9-480f-8016-c3be0cc40526

Preview of Book Cover Image
